name: appium Test

on:
  workflow_dispatch:

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      android-container:
        image: budtmo/docker-android:emulator_11.0
        options: >-
          -e EMULATOR_DEVICE="Samsung Galaxy S10" 
          -e WEB_VNC=true 
          -e APPIUM=true 
          --device /dev/kvm
        
        ports:
          - 6080:6080
          - 4723:4723
          - 5555:5555
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install Appium-Python-Client
          apt update
          apy install python3
          python3 --version

      - name: Run Tests
        run: |
          python appium2/Test_manual_open.py
