name: appium Test

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - device: "Samsung Galaxy S10"
            dir: "s10"
          - device: "Samsung Galaxy S9"
            dir: "s9"
          - device: "Samsung Galaxy S8"
            dir: "s8"
          - device: "Samsung Galaxy S7"
            dir: "s7"
    services:
      android-container:
        image: budtmo/docker-android:emulator_11.0
        options: >-
          -e EMULATOR_DEVICE="${{ matrix.config.device }}"
          -e WEB_VNC=true 
          -e APPIUM=true 
          -e CHROMEDRIVER_AUTODOWNLOAD=true
          -e APPIUM_ADDITIONAL_ARGS="--allow-insecure chromedriver_autodownload"
          --device /dev/kvm
        ports:
          - 6080:6080
          - 4723:4723
          - 5555:5555

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies and pull 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g allure-commandline

      - name: Wait for the emulator to start
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '60' # for 60 seconds

      - name: Run Test
        if: always()
        run: python -m pytest --alluredir allure-results
        continue-on-error: true
      
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure_report-${{ matrix.config.dir }}
          path: allure-report
          retention-days: 3