name: appium Test

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - device: "Samsung Galaxy S10"
            dir: "s10"
          - device: "Samsung Galaxy S9"
            dir: "s9"
    services:
      android-container:
        image: budtmo/docker-android:emulator_11.0
        options: >-
          -e EMULATOR_DEVICE="${{ matrix.config.device }}"
          -e WEB_VNC=true 
          -e APPIUM=true 
          -e CHROMEDRIVER_AUTODOWNLOAD=true
          -e APPIUM_ADDITIONAL_ARGS="--allow-insecure chromedriver_autodownload"
          --device /dev/kvm
        ports:
          - 6080:6080
          - 4723:4723
          - 5555:5555

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and pull 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          git pull

      - name: Wait for the emulator to start
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '60' # for 60 seconds

      - name: Run Test
        if: always()
        run: python -m pytest --alluredir allure-results
        continue-on-error: true
  
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gitHubTests
          path: gitHubTests

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gitHubTests
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gitHubTests
          publish_dir: allure-history